CREATE DATABASE Hitaya_Tax
GO

USE Hitaya_Tax
GO


CREATE TABLE USERDETAILS
(
	[USERID] INT IDENTITY(1000,1),
	[FIRSTNAME] VARCHAR(20) NOT NULL,
	[LASTNAME] VARCHAR(20) NOT NULL,
	[EMAILID] VARCHAR(20)  NOT NULL,
	[PAN_CARD] VARCHAR(20) CONSTRAINT pk_PanCard PRIMARY KEY,
	[PASSWORD] VARCHAR(20) NOT NULL,
	[PHONE_NUMBER] VARCHAR(20) NOT NULL,
	[ADDRESS] VARCHAR(100) NOT NULL,
	[ROLEID] VARCHAR(20) NOT NULL CONSTRAINT chk_Role CHECK ([ROLEID] IN ('Admin','User'))
)
GO 


CREATE PROCEDURE usp_RegisterUser
(
	@FIRSTNAME VARCHAR(20),
	@LASTNAME VARCHAR(20),
	@EMAILID VARCHAR(20),
	@PAN_CARD VARCHAR(20),
	@PASSWORD VARCHAR(20),
	@PHONE_NUMBER VARCHAR(20),
	@ADDRESS VARCHAR(100)
)
AS
BEGIN
	DECLARE @RoleId TINYINT
	BEGIN TRY
		INSERT INTO USERDETAILS(FIRSTNAME,LASTNAME,EMAILID,PAN_CARD,PASSWORD,PHONE_NUMBER,ADDRESS,ROLEID) 
		VALUES (@FIRSTNAME,@LASTNAME,@EMAILID,@PAN_CARD,@PASSWORD,@PHONE_NUMBER,@ADDRESS,'User')
		RETURN 1
	END TRY
	BEGIN CATCH
		RETURN -99
	END CATCH
END
GO


DECLARE @RETURNVAL INT
EXEC @RETURNVAL = usp_RegisterUser 'Arnab','Das','trisha@gmail.com','CGDPD1480N', '12345678','9547966499', 'Desh Bandhu Park, Raod No-2'
SELECT @RETURNVAL AS RETURNVAL


SELECT * FROM USERDETAILS


CREATE PROCEDURE usp_LoginValidation
(
	@PAN_CARD VARCHAR(20),
	@PASSWORD VARCHAR(20)
)
AS
BEGIN
	DECLARE @RoleId TINYINT
	BEGIN TRY
		IF EXISTS (SELECT * FROM USERDETAILS WHERE PAN_CARD=@PAN_CARD AND PASSWORD=@PASSWORD)
			RETURN 1
		ELSE
			RETURN -1
	END TRY
	BEGIN CATCH
		RETURN -99
	END CATCH
END
GO


DECLARE @RETURNVAL INT
EXEC @RETURNVAL = usp_LoginValidation 'CGDPD1480N0', '12345678'
SELECT @RETURNVAL AS RETURNVAL



CREATE TABLE TAX_FILLING
(
	[TAX_ID] INT IDENTITY(1000,1),
	[PAN_CARD] VARCHAR(20)  NOT NULL FOREIGN KEY REFERENCES USERDETAILS([PAN_CARD]),
	[FILLING_YEAR] VARCHAR(20) NOT NULL,
	[TOTAL_YEARLY_INCOME] DECIMAL(20,2) NOT NULL,
	[Standard_Deduction] DECIMAL(20,2) NOT NULL,
	[80C_80CCC] DECIMAL(10,2) NOT NULL,
	[80D_HIP_Self] DECIMAL(10,2) NOT NULL,
	[80D_HIP_Parents] DECIMAL(10,2) NOT NULL,
	[80CCD_1B] DECIMAL(10,2) NOT NULL,
	[80CCD_2] DECIMAL(10,2) NOT NULL,
	[80E] DECIMAL(10,2) NOT NULL,
	[80U] DECIMAL(10,2) NOT NULL,
	[80DD] DECIMAL(10,2) NOT NULL,
	[80DDB] DECIMAL(10,2) NOT NULL,
	[80TTA] DECIMAL(10,2) NOT NULL,
	[TDS_PAID] DECIMAL(10,2) NOT NULL,
	[ADVANCE_TAX_PAID] DECIMAL(10,2) NOT NULL,
	[TOTAL_TAXABLE_INCOME] DECIMAL(20,2) NOT NULL,
	[TAX_TO_BE_PAID_REFUNDED] DECIMAL(10,2) NOT NULL,
	[FORM_SUBMITTED] VARCHAR(20) NOT NULL CONSTRAINT chk_Form CHECK ([FORM_SUBMITTED]  IN ('Yes','No')),
	[STATUS] VARCHAR(20) NOT NULL CONSTRAINT chk_Status CHECK ([STATUS]  IN ('Rejected','Pending', 'Approved')),
	Constraint PK_TAX Primary Key ([PAN_CARD], [FILLING_YEAR])
)
GO 



