CREATE DATABASE Hitaya_Tax
GO

USE Hitaya_Tax
GO


CREATE TABLE USERDETAILS
(
	[USERID] INT IDENTITY(1000,1),
	[FIRSTNAME] VARCHAR(20) NOT NULL,
	[LASTNAME] VARCHAR(20) NOT NULL,
	[EMAILID] VARCHAR(20)  NOT NULL,
	[PAN_CARD] VARCHAR(20) CONSTRAINT pk_PanCard PRIMARY KEY,
	[PASSWORD] VARCHAR(20) NOT NULL,
	[PHONE_NUMBER] VARCHAR(20) NOT NULL,
	[ADDRESS] VARCHAR(100) NOT NULL,
	[ROLEID] VARCHAR(20) NOT NULL CONSTRAINT chk_Role CHECK ([ROLEID] IN ('Admin','User'))
)
GO 

IF OBJECT_ID('USERDETAILS')  IS NOT NULL
DROP TABLE USERDETAILS
GO


CREATE PROCEDURE usp_RegisterUser
(
	@FIRSTNAME VARCHAR(20),
	@LASTNAME VARCHAR(20),
	@EMAILID VARCHAR(20),
	@PAN_CARD VARCHAR(20),
	@PASSWORD VARCHAR(20),
	@PHONE_NUMBER VARCHAR(20),
	@ADDRESS VARCHAR(100)
)
AS
BEGIN
	DECLARE @RoleId TINYINT
	BEGIN TRY
		INSERT INTO USERDETAILS(FIRSTNAME,LASTNAME,EMAILID,PAN_CARD,PASSWORD,PHONE_NUMBER,ADDRESS,ROLEID) 
		VALUES (@FIRSTNAME,@LASTNAME,@EMAILID,@PAN_CARD,@PASSWORD,@PHONE_NUMBER,@ADDRESS,'User')
		RETURN 1
	END TRY
	BEGIN CATCH
		RETURN -99
	END CATCH
END
GO


DECLARE @RETURNVAL INT
EXEC @RETURNVAL = usp_RegisterUser 'Arnab','Das','trisha@gmail.com','CGDPD1480N', '12345678','9547966499', 'Desh Bandhu Park, Raod No-2'
SELECT @RETURNVAL AS RETURNVAL


SELECT * FROM USERDETAILS


CREATE PROCEDURE usp_LoginValidation
(
	@PAN_CARD VARCHAR(20),
	@PASSWORD VARCHAR(20)
)
AS
BEGIN
	DECLARE @RoleId TINYINT
	BEGIN TRY
		IF EXISTS (SELECT * FROM USERDETAILS WHERE PAN_CARD=@PAN_CARD AND PASSWORD=@PASSWORD)
			RETURN 1
		ELSE
			RETURN -1
	END TRY
	BEGIN CATCH
		RETURN -99
	END CATCH
END
GO


DECLARE @RETURNVAL INT
EXEC @RETURNVAL = usp_LoginValidation 'CGDPD1480N', '12345678'
SELECT @RETURNVAL AS RETURNVAL



CREATE TABLE TAX_FILLING
(
	[TAX_ID] INT IDENTITY(1000,1),
	[PAN_CARD] VARCHAR(20)  NOT NULL FOREIGN KEY REFERENCES USERDETAILS([PAN_CARD]),
	[FILLING_YEAR] VARCHAR(20) NOT NULL,
	[TOTAL_YEARLY_INCOME] DECIMAL(20,2) NOT NULL,
	[Standard_Deduction] DECIMAL(20,2) NOT NULL,
	[80C_80CCC] DECIMAL(10,2) NOT NULL,
	[80D_HIP_Self] DECIMAL(10,2) NOT NULL,
	[80D_HIP_Parents] DECIMAL(10,2) NOT NULL,
	[80CCD_1B] DECIMAL(10,2) NOT NULL,
	[80CCD_2] DECIMAL(10,2) NOT NULL,
	[80E] DECIMAL(10,2) NOT NULL,
	[80U] DECIMAL(10,2) NOT NULL,
	[80DD] DECIMAL(10,2) NOT NULL,
	[80DDB] DECIMAL(10,2) NOT NULL,
	[80TTA] DECIMAL(10,2) NOT NULL,
	[TDS_PAID] DECIMAL(10,2) NOT NULL,
	[ADVANCE_TAX_PAID] DECIMAL(10,2) NOT NULL,
	[TOTAL_TAXABLE_INCOME] DECIMAL(20,2) NOT NULL,
	[TAX_TO_BE_PAID_REFUNDED] DECIMAL(10,2) NOT NULL,
	[FORM_SUBMITTED] VARCHAR(20) NOT NULL CONSTRAINT chk_Form CHECK ([FORM_SUBMITTED]  IN ('Yes','No')),
	[STATUS] VARCHAR(20) NOT NULL CONSTRAINT chk_Status CHECK ([STATUS]  IN ('Rejected','Pending', 'Approved')),
	Constraint PK_TAX Primary Key ([PAN_CARD], [FILLING_YEAR])
)
GO 





CREATE PROCEDURE USP_TAX_FILLING
(
	@PAN_CARD VARCHAR(20),
	@FILLING_YEAR VARCHAR(20),
	@TOTAL_YEARLY_INCOME DECIMAL(20,2),
	@Standard_Deduction DECIMAL(20,2),
	@80C_80CCC DECIMAL(10,2),
	@80D_HIP_Self DECIMAL(10,2),
	@80D_HIP_Parents DECIMAL(10,2),
	@80CCD_1B DECIMAL(10,2),
	@80CCD_2 DECIMAL(10,2),
	@80E DECIMAL(10,2),
	@80U DECIMAL(10,2),
	@80DD DECIMAL(10,2),
	@80DDB DECIMAL(10,2),
	@80TTA DECIMAL(10,2),
	@TDS_PAID DECIMAL(10,2),
	@ADVANCE_TAX_PAID DECIMAL(10,2),
	@TOTAL_TAXABLE_INCOME DECIMAL(20,2),
	@TAX_TO_BE_PAID_REFUNDED DECIMAL(10,2),
	@FORM_SUBMITTED VARCHAR(20),
	@STATUS VARCHAR(20)
)
AS
BEGIN
	DECLARE @RoleId TINYINT
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM USERDETAILS WHERE PAN_CARD=@PAN_CARD)
		RETURN -1
		INSERT INTO TAX_FILLING([PAN_CARD],[FILLING_YEAR],[TOTAL_YEARLY_INCOME],[Standard_Deduction],[80C_80CCC],[80D_HIP_Self],[80D_HIP_Parents],[80CCD_1B],[80CCD_2],[80E],[80U],
		[80DDB],[80TTA],[TDS_PAID],[ADVANCE_TAX_PAID],[TOTAL_TAXABLE_INCOME],[TAX_TO_BE_PAID_REFUNDED],[FORM_SUBMITTED],[STATUS]) 
		VALUES (@PAN_CARD,@FILLING_YEAR,@TOTAL_YEARLY_INCOME,@Standard_Deduction,@80C_80CCC,@80D_HIP_Self,@80D_HIP_Parents,
		@80CCD_1B,@80CCD_2,@80E,@80U,@80DD,@80DDB,@80TTA,@TDS_PAID,@ADVANCE_TAX_PAID,@TAX_TO_BE_PAID_REFUNDED,@FORM_SUBMITTED,@STATUS)
		RETURN 1
	END TRY
	BEGIN CATCH
		RETURN -99
	END CATCH
END
GO

IF OBJECT_ID('USP_TAX_FILLING')  IS NOT NULL
DROP PROC USP_TAX_FILLING
GO


DECLARE @RETURNVAL INT
EXEC @RETURNVAL = USP_TAX_FILLING 'CGDPD1480N', '2021-2023', 700000.32, 50000.00, 76000.23, 25000, 50000, 10000, 6000, 0, 0, 0, 0, 500, 3000, 500,0,0, 'Yes', 'Pending'
SELECT @RETURNVAL AS RETURNVAL

INSERT INTO TAX_FILLING([PAN_CARD],[FILLING_YEAR],[TOTAL_YEARLY_INCOME],[Standard_Deduction],[80C_80CCC],[80D_HIP_Self],[80D_HIP_Parents],[80CCD_1B],[80CCD_2],[80E],[80U],[80DD],
		[80DDB],[80TTA],[TDS_PAID],[ADVANCE_TAX_PAID],[TOTAL_TAXABLE_INCOME],[TAX_TO_BE_PAID_REFUNDED],[FORM_SUBMITTED],[STATUS]) 
		VALUES ('CGDPD1480NA', '2022-2023', 700000.32, 50000.00, 76000.23, 25000, 50000, 10000, 6000, 0, 0, 0, 0, 500, 
		3000, 500,0,0, 'Yes', 'Pending')

SELECT * FROM TAX_FILLING