export interface ITax {
  PAN_CARD : string,
  FILLING_YEAR: string,
  FILLING_STATUS: string,
  ITR_FORM: string,
  REASON: string,
  TAX_REGIME: string,
  TOTAL_YEARLY_INCOME: number,
  Standard_Deduction: number,
	_80C_80CCC: number,
  _80D_HIP_Self: number,
  _80D_HIP_Parents: number,
  _80CCD_1B: number,
  _80CCD_2: number,
  _80E: number,
  _80U: number,
  _80DD: number,
  _80DDB: number,
  _80TTA: number,
  TDS_PAID: number,
  ADVANCE_TAX_PAID: number,
  TOTAL_TAXABLE_INCOME: number,
  TAX_TO_BE_PAID_REFUNDED: number,
	FORM_SUBMITTED: string,
	STATUS: string
}
