export interface ITax {
  panCard : string,
  fillingYear: string,
  fillingStatus: string,
  itrForm: string,
  reason: string,
  taxRegime: string,
  totalYearlyIncome: number,
  standardDeduction: number,
  _80c80ccc: number,
  _80dHipSelf: number,
  _80dHipParents: number,
  _80ccd1b: number,
  _80ccd2: number,
  _80e: number,
  _80u: number,
  _80dd: number,
  _80ddb: number,
  _80tta: number,
  tdsPaid: number,
  advanceTaxPaid: number,
  totalTaxableIncome: number,
  taxToBePaidRefunded: number,
  formSubmitted: string,
  status: string
}
